### PR TITLE
fixed the null reference exception in fetch/get user by id request #17

### LINKED ISSUE #17: A null reference was detected in fetch user by id
- An null reference exception not set to an instance of an object in user id
- Return not found, if user is null

### PR DESCRIPTION
**Pull request by giddy11**
this fixes #17

### CODE REVIEW

**Review by Suzee27 — APPROVED** [review]
Nice work!

**Comment by giddy11** [comment]
this fixes #17

**Review by Samuel-Jaja — COMMENTED** [review]
Not a bad one

**Comment by giddy11** [comment]
Thanks brother

**Pull request merged**
